infinispan.client.hotrod.server_list=localhost:11222
infinispan.client.hotrod.auth_username=admin
infinispan.client.hotrod.auth_password=changeit
infinispan.client.hotrod.auth_realm=default
infinispan.client.hotrod.sasl_mechanism=SCRAM-SHA-512
